services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:16-alpine}
    container_name: ${POSTGRES_CONTAINER_NAME:-wedding_postgres}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 10

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: deps
  #   container_name: ${API_CONTAINER_NAME:-wedding_api}
  #   restart: unless-stopped
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   command: npm run start:dev
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     NODE_ENV: ${NODE_ENV}
  #     PORT: ${API_INTERNAL_PORT:-3000}
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: 5432
  #     DB_USERNAME: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_NAME: ${DB_NAME}
  #     DB_SYNC: ${DB_SYNC}
  #     JWT_SECRET: ${JWT_SECRET}
  #     JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     CHOKIDAR_USEPOLLING: 'true'
  #     CHOKIDAR_INTERVAL: '300'
  #   ports:
  #     - '${PORT}:${API_INTERNAL_PORT:-3000}'

  redis:
    image: redis:7-alpine
    container_name: ${REDIS_CONTAINER_NAME:-wedding_redis}
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'

volumes:
  postgres_data:
